os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

before_install:
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
  fi
# add dependencies to compile node-hid (no prebuilt available)
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    yarn global add node-gyp
  fi

install:
- source ./scripts/retry.sh
- retry 3 yarn install

before_script:
# Make variables and function from Travis available in our script
# See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
# and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
- export ANSI_CLEAR
- export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish

# Use Docker if available (currently Linux only)
# macOS/Linux compatible temp dir deleted on reboot (https://stackoverflow.com/a/31397073)
- |
  if which docker > /dev/null ; then
    export TM_VERSION=0.21.0
    export BOV_VERSION=v0.6.0
    docker pull tendermint/tendermint:${TM_VERSION}
    docker pull iov1/tendermint:${TM_VERSION}
    docker pull iov1/bov:${BOV_VERSION}
    export TENDERMINT_ENABLED=1
    export BOV_ENABLED=1

    export TM_DIR=$(mktemp -d "${TMPDIR:-/tmp}/tendermint_${TM_VERSION}.XXXXXXXXX")
    export BOV_DIR=$(mktemp -d "${TMPDIR:-/tmp}/bov_${BOV_VERSION}.XXXXXXXXX")
    echo "TM_DIR = $TM_DIR"
    echo "BOV_DIR = $BOV_DIR"

    ./packages/iov-tendermint-rpc/tendermint.sh > /tmp/foo.log &
    export TM_PID=$!
    echo "Started tendermint" $TM_PID
    sleep 2

    ./packages/iov-bns/bov_init.sh
    ./packages/iov-bns/bov_tm.sh > /tmp/bov_tm.log &
    export BOV_TM_PID=$!
    ./packages/iov-bns/bov_app.sh > /tmp/bov_app.log &
    export BOV_APP_PID=$!
    sleep 3
    # for debug output
    cat /tmp/bov_tm.log
    cat /tmp/bov_app.log
  fi

script:
- echo "use tendermint?" ${TENDERMINT_ENABLED} "use bov?" ${BOV_ENABLED}
- ./scripts/travis.sh

after_script:
- |
  if [[ $TM_PID ]]; then
    echo "Stopping tendermint" $TM_PID
    kill ${TM_PID}
  fi
- |
  if [[ $BOV_APP_PID ]]; then
    echo "Stopping bov"
    kill ${BOV_APP_PID}
    kill ${BOV_TM_PID}
    # for debug output
    cat /tmp/bov_app.log
  fi

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
